/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
    | 'Pacific/Midway'
    | 'Pacific/Niue'
    | 'Pacific/Honolulu'
    | 'Pacific/Rarotonga'
    | 'America/Anchorage'
    | 'Pacific/Gambier'
    | 'America/Los_Angeles'
    | 'America/Tijuana'
    | 'America/Denver'
    | 'America/Phoenix'
    | 'America/Chicago'
    | 'America/Guatemala'
    | 'America/New_York'
    | 'America/Bogota'
    | 'America/Caracas'
    | 'America/Santiago'
    | 'America/Buenos_Aires'
    | 'America/Sao_Paulo'
    | 'Atlantic/South_Georgia'
    | 'Atlantic/Azores'
    | 'Atlantic/Cape_Verde'
    | 'Europe/London'
    | 'Europe/Berlin'
    | 'Africa/Lagos'
    | 'Europe/Athens'
    | 'Africa/Cairo'
    | 'Europe/Moscow'
    | 'Asia/Riyadh'
    | 'Asia/Dubai'
    | 'Asia/Baku'
    | 'Asia/Karachi'
    | 'Asia/Tashkent'
    | 'Asia/Calcutta'
    | 'Asia/Dhaka'
    | 'Asia/Almaty'
    | 'Asia/Jakarta'
    | 'Asia/Bangkok'
    | 'Asia/Shanghai'
    | 'Asia/Singapore'
    | 'Asia/Tokyo'
    | 'Asia/Seoul'
    | 'Australia/Brisbane'
    | 'Australia/Sydney'
    | 'Pacific/Guam'
    | 'Pacific/Noumea'
    | 'Pacific/Auckland'
    | 'Pacific/Fiji';

export interface Config {
    auth: {
        users: UserAuthOperations;
    };
    blocks: {};
    collections: {
        users: User;
        media: Media;
        stories: Story;
        comments: Comment;
        articles: Article;
        organizations: Organization;
        'payload-kv': PayloadKv;
        'payload-locked-documents': PayloadLockedDocument;
        'payload-preferences': PayloadPreference;
        'payload-migrations': PayloadMigration;
    };
    collectionsJoins: {};
    collectionsSelect: {
        users: UsersSelect<false> | UsersSelect<true>;
        media: MediaSelect<false> | MediaSelect<true>;
        stories: StoriesSelect<false> | StoriesSelect<true>;
        comments: CommentsSelect<false> | CommentsSelect<true>;
        articles: ArticlesSelect<false> | ArticlesSelect<true>;
        organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
        'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
        'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
        'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
        'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    };
    db: {
        defaultIDType: string;
    };
    fallbackLocale: null;
    globals: {};
    globalsSelect: {};
    locale: null;
    user: User & {
        collection: 'users';
    };
    jobs: {
        tasks: unknown;
        workflows: unknown;
    };
}
export interface UserAuthOperations {
    forgotPassword: {
        email: string;
        password: string;
    };
    login: {
        email: string;
        password: string;
    };
    registerFirstUser: {
        email: string;
        password: string;
    };
    unlock: {
        email: string;
        password: string;
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
    id: string;
    updatedAt: string;
    createdAt: string;
    email: string;
    resetPasswordToken?: string | null;
    resetPasswordExpiration?: string | null;
    salt?: string | null;
    hash?: string | null;
    loginAttempts?: number | null;
    lockUntil?: string | null;
    sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
    }[]
    | null;
    password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
    id: string;
    alt: string;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
    id: string;
    title: string;
    slug?: string | null;
    author: string;
    authorRole?: string | null;
    email?: string | null;
    excerpt?: string | null;
    body: {
        [k: string]: unknown;
    }[];
    category?: ('personal' | 'organization' | 'family' | 'professional') | null;
    status?: ('draft' | 'pending' | 'published' | 'rejected') | null;
    adminNotes?: string | null;
    featuredImage?: (string | null) | Media;
    publishedAt?: string | null;
    responses?:
    | {
        responderName: string;
        responderRole?: string | null;
        message: string;
        respondedAt?: string | null;
        id?: string | null;
    }[]
    | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
    id: string;
    authorName: string;
    message: string;
    isTeamMember?: boolean | null;
    teamRole?: string | null;
    status?: ('pending' | 'approved' | 'rejected') | null;
    relationType: 'story' | 'organization';
    story?: (string | null) | Story;
    organization?: (string | null) | Organization;
    moderationScore?: number | null;
    moderationReason?: string | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
    id: string;
    title: string;
    slug?: string | null;
    body: {
        [k: string]: unknown;
    }[];
    category?: ('prevention' | 'health' | 'parents' | 'education' | 'guide') | null;
    featuredImage?: (string | null) | Media;
    author?: string | null;
    status?: ('draft' | 'published') | null;
    publishedAt?: string | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
    id: string;
    name: string;
    slug?: string | null;
    description?: {
        [k: string]: unknown;
    }[] | null;
    logo?: (string | null) | Media;
    website?: string | null;
    type?: ('supporter' | 'partner' | 'clinic' | 'school') | null;
    status?: ('pending' | 'approved' | 'rejected') | null;
    adminNotes?: string | null;
    approvedAt?: string | null;
    featured?: boolean | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
    id: string;
    key: string;
    data:
    | {
        [k: string]: unknown;
    }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
    id: string;
    document?:
    | ({
        relationTo: 'users';
        value: string | User;
    } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
    } | null)
    | ({
        relationTo: 'stories';
        value: string | Story;
    } | null)
    | ({
        relationTo: 'comments';
        value: string | Comment;
    } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
    } | null)
    | ({
        relationTo: 'organizations';
        value: string | Organization;
    } | null);
    globalSlug?: string | null;
    user: {
        relationTo: 'users';
        value: string | User;
    };
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
    id: string;
    user: {
        relationTo: 'users';
        value: string | User;
    };
    key?: string | null;
    value?:
    | {
        [k: string]: unknown;
    }
    | unknown[]
    | string
    | number
    | boolean
    | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
    id: string;
    name?: string | null;
    batch?: number | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
    updatedAt?: T;
    createdAt?: T;
    email?: T;
    resetPasswordToken?: T;
    resetPasswordExpiration?: T;
    salt?: T;
    hash?: T;
    loginAttempts?: T;
    lockUntil?: T;
    sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
    alt?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
    title?: T;
    slug?: T;
    author?: T;
    authorRole?: T;
    email?: T;
    excerpt?: T;
    body?: T;
    category?: T;
    status?: T;
    adminNotes?: T;
    featuredImage?: T;
    publishedAt?: T;
    responses?:
    | T
    | {
        responderName?: T;
        responderRole?: T;
        message?: T;
        respondedAt?: T;
        id?: T;
    };
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
    authorName?: T;
    message?: T;
    isTeamMember?: T;
    teamRole?: T;
    status?: T;
    relationType?: T;
    story?: T;
    organization?: T;
    moderationScore?: T;
    moderationReason?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
    title?: T;
    slug?: T;
    body?: T;
    category?: T;
    featuredImage?: T;
    author?: T;
    status?: T;
    publishedAt?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
    name?: T;
    slug?: T;
    description?: T;
    logo?: T;
    website?: T;
    type?: T;
    status?: T;
    adminNotes?: T;
    approvedAt?: T;
    featured?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
    key?: T;
    data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
    document?: T;
    globalSlug?: T;
    user?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
    user?: T;
    key?: T;
    value?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
    name?: T;
    batch?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
    [k: string]: unknown;
}


declare module 'payload' {
    export interface GeneratedTypes extends Config { }
}
