// Article data for seeding — extracted from the original resurse/page.tsx
// Each article has its text content split into paragraphs for Lexical conversion

interface SeedArticle {
    slug: string
    title: string
    category: string
    author?: string
    publishedAt: string
    body: string[]
}

export const articles: SeedArticle[] = [
    {
        slug: 'prezentarea-asociatiei-pdf',
        title: 'Prezentarea Asociației — PDF',
        category: 'education',
        publishedAt: '2025-08-01',
        body: [
            'Deschide și consultă prezentarea asociației în format PDF. Poți și descărca documentul.',
            'Prezentarea oficială a Asociației „Drogurile Ucid Visurile Copiilor" este disponibilă pentru descărcare pe site-ul nostru.',
        ],
    },
    {
        slug: 'spune-nu-drogurilor',
        title: '🚫 SPUNE NU DROGURILOR! 🚫',
        category: 'prevention',
        publishedAt: '2025-08-02',
        body: [
            'Substanțe care îți schimbă corpul și mintea. Promit distracție, dar aduc doar probleme.',
            '❓ Ce sunt drogurile? Substanțe care îți schimbă corpul și mintea. Promit distracție, dar aduc doar probleme.',
            '⚠️ De ce să NU consumi? Îți distrug sănătatea. Îți scad memoria și concentrarea. Creează dependență. Îți pun viitorul în pericol. Îți îndepărtează familia și prietenii.',
            '❌ Riscuri majore: Boli grave și accidente. Anxietate și depresie. Probleme cu legea. Izolare socială.',
            '✅ Cum să spui „NU"? Fii ferm: „Nu, nu vreau!" Pleacă din situațiile riscante. Alege alternative sănătoase: sport, muzică, lectură. Înconjoară-te de prieteni adevărați.',
            '🆘 Dacă cineva consumă deja… Vorbește cu un adult de încredere. Cere ajutor specializat. Nu te învinovăți, caută soluții!',
            '🔑 Concluzie: Drogurile nu aduc libertate. Aduc boală, dependență și tristețe. Alege să fii sănătos, fericit și liber! 🌟',
            'Asociația „Drogurile Ucid Visurile Copiilor"',
        ],
    },
    {
        slug: 'povestea-eroul-alex-si-monstrul-drog',
        title: 'Povestea lui Eroul Alex și Monstrul Drog 🦸‍♀️',
        category: 'education',
        publishedAt: '2025-08-03',
        body: [
            'Demult, într-un oraș liniștit, trăia un băiat curajos pe nume Alex. El visa să devină supererou adevărat, care să salveze oamenii și să aducă bucurie.',
            'Dar într-o zi, din umbra străzilor a apărut un monstru periculos numit Drog. Avea ochi strălucitori și șoptea: – „Vino cu mine, Alex! Îți voi da puteri magice și distracție fără sfârșit…"',
            'Monstrul părea prietenos, dar în spatele lui se ascundeau lanțuri negre și o pelerină întunecată care înfășura pe oricine cădea în capcana lui.',
            '⚠️ Alex a văzut ce făcea Monstrul Drog oamenilor: Le fura sănătatea, făcându-le inimile și mințile slabe. Le răpea memoria și bucuria. Îi lega cu lanțuri grele de dependență. Le distrugea visurile și îi îndepărta de familie. Îi trimitea pe un drum fără viitor. „Nu, nu asta vreau eu!" și-a spus Alex.',
            '✅ Atunci, băiatul și-a scos scutul curajului și a strigat: – „NU, Monstru Drog! Puterea mea este mai mare decât minciunile tale!" Cu un pas hotărât, Alex a fugit din locul întunecat și a ales să meargă la prietenii lui. Acolo, cu mingea, muzica și cărțile, și-a găsit adevărata bucurie.',
            '🆘 Dar Alex a înțeles și ceva important: Dacă un prieten cădea în ghearele Monstrului Drog, nu trebuia să lupte singur. El știa că poate cere ajutor de la înțelepții adulți: părinți, profesori sau doctori. Aceștia aveau arme speciale – înțelepciunea și grija – cu care puteau slăbi puterea monstrului.',
            '🔑 Morala basmului: Monstrul Drog promite magie, dar aduce doar boală și lanțuri. Adevărații eroi aleg sănătatea, prietenia și visele lor luminoase. 🌟 Fii eroul poveștii tale! Spune NU Monstrului Drog și păstrează-ți libertatea!',
        ],
    },
    {
        slug: 'cum-iti-dai-seama-ca-un-prieten-are-probleme-cu-drogurile',
        title: 'Cum îți dai seama că un prieten sau chiar tu ai putea să ai probleme cu drogurile',
        category: 'health',
        author: 'Psiholog Mihaela Sava',
        publishedAt: '2025-08-04',
        body: [
            'La adolescență este normal să treci prin schimbări de dispoziție, dar uneori unele semne pot arăta că cineva începe să aibă probleme cu drogurile. Este important să le recunoști și să ceri ajutor la timp.',
            'Semne fizice: Ochii roșii sau foarte strălucitori, pupile prea mici sau prea mari. Slăbire sau îngrășare bruscă. Somn foarte puțin sau prea mult. Lipsa de chef să ai grijă de igiena ta. Haine sau cameră cu mirosuri ciudate.',
            'Semne de comportament: Nu mai ai chef de hobby-uri sau activități care îți plăceau. Îți schimbi prietenii brusc, fără să spui prea multe despre ei. Spui minciuni mai des, ascunzi lucruri. Începi să lipsești de la școală și notele scad. Devii foarte nervos, agresiv sau dimpotrivă, retras și trist.',
            'Semne emoționale: Schimbări bruște de dispoziție (de la fericire la furie sau tristețe). Te enervezi repede sau devii foarte anxios. Ai stări de confuzie sau teamă fără motiv clar.',
            'Cum să vorbești despre asta: Alege un moment liniștit – nu când e ceartă sau tensiune. Vorbește deschis – de exemplu: „Nu mă simt bine în ultima vreme și am nevoie de ajutor." Ascultă și fii sincer – nu te grăbi să negi sau să te aperi. Recunoaște ce simți – uneori drogurile sunt folosite ca să ascundă stresul, tristețea sau presiunea. Gândește-te că nu ești singur – familia și prietenii apropiați pot fi alături de tine.',
            'De ce e importantă terapia: Un terapeut nu e un polițist și nici un judecător. Este o persoană care te poate ajuta să înțelegi ce se întâmplă cu tine și să găsești soluții. Poți merge împreună cu cineva apropiat. Terapia nu e o pedeapsă, ci o cale de a te simți mai bine și de a recăpăta controlul. Este normal să îți fie teamă sau rușine, dar asta nu înseamnă că ești „defect".',
            'Nu rămâne singur! Dacă simți că ai început să consumi droguri sau ai un prieten care trece prin asta, vorbește cu un adult de încredere: un părinte, un profesor, un medic sau un consilier școlar. Cu cât ceri mai repede ajutor, cu atât îți va fi mai ușor să-ți revii și să-ți construiești un viitor sănătos.',
        ],
    },
    {
        slug: '5-semne-ca-se-intampla-ceva-cu-adolescentul-tau',
        title: '5 semne că se întâmplă ceva cu adolescentul tău (și nu e de bine)',
        category: 'parents',
        author: 'Nina Buru, Psiholog Sportiv',
        publishedAt: '2025-09-27',
        body: [
            'Adolescența nu este doar o etapă de descoperiri și entuziasm. Este și o perioadă plină de încercări, în care echilibrul emoțional și alegerile corecte pot face diferența între un drum sănătos și unul periculos.',
            'Pentru părinți, provocarea cea mai mare este să recunoască la timp semnele că fiul sau fiica lor trece printr-o situație dificilă.',
            '1. Devine foarte secretos: Telefonul devine un teritoriu interzis, dispar conversațiile de la cină și evită privirea ochi în ochi. Intimitatea este firească la această vârstă, dar atunci când secretomania devine excesivă, părinții trebuie să fie atenți.',
            '2. Își schimbă brusc prietenii: La 16–17 ani, prieteniile cântăresc enorm. Dar schimbarea bruscă a anturajului și tăcerea în privința celor noi pot fi semne că adolescentul caută altceva: validare, apartenență, sau, mai grav, expunere la tentații.',
            '3. Probleme cu banii: Cere mai mulți bani decât de obicei, dispar sume din casă, iar explicațiile lipsesc. De multe ori, banii sunt primul indicator că adolescentul este presat de cineva sau începe să experimenteze comportamente riscante.',
            '4. Schimbări de comportament și dispoziție: De la irascibilitate și retragere până la nopți pierdute și somn excesiv, schimbările bruște de comportament nu trebuie ignorate.',
            '5. Pierde interesul pentru școală și activități: Scad notele, dispare motivația, hobby-urile rămân uitate într-un colț.',
            'Drogurile ucid visele copiilor. Drogurile nu fură doar sănătatea, ci și viitorul. Ele schimbă chimia creierului și răpesc plăcerile simple ale vieții. Dopamina, motorul motivației, este supraîncărcată și apoi slăbită. Serotonina, responsabilă de echilibru emoțional, se dezechilibrează. Noradrenalina, care ține atenția trează, este distorsionată.',
            'Context românesc – cifre care dor: 3 din 10 adolescenți spun că știu pe cineva care consumă droguri. 8,7% dintre adolescenții sub 16 ani au încercat canabis cel puțin o dată. Vârsta de debut a scăzut alarmant, ajungând la 13–14 ani.',
            'Cum poate sportul să refacă echilibrul? Sportul este un aliat puternic. Activitatea fizică reface în mod natural echilibrul neurotransmițătorilor: Dopamina – fiecare antrenament aduce satisfacție și motivație reală. Serotonina – exercițiile regulate îmbunătățesc starea de spirit. Endorfinele – oferă un „high" natural și sănătos.',
            'Dragi părinți, întrebați-vă: Ce fel de centură de siguranță are adolescentul vostru?',
        ],
    },
    {
        slug: 'ghid-pdf-preventie-si-sprijin',
        title: 'Ghid PDF: Prevenție și sprijin pentru părinți și elevi',
        category: 'guide',
        publishedAt: '2025-08-05',
        body: [
            'Deschide și consultă ghidul complet în format PDF. Poți și descărca documentul.',
            'Ghidul complet de prevenție și sprijin pentru părinți și elevi, realizat de ANPCDDA (2025), este disponibil pentru consultare și descărcare pe site-ul nostru.',
        ],
    },
    {
        slug: 'semne-care-indica-consum-droguri',
        title: 'Semne care indică faptul că un copil ar putea consuma droguri',
        category: 'parents',
        publishedAt: '2025-08-06',
        body: [
            'Este normal ca adolescenții să treacă prin schimbări de dispoziție, dar este important să fii atent la semnele care depășesc comportamentul tipic.',
            'Detectarea timpurie a consumului de droguri poate fi crucială. Iată câteva semne la care ar trebui să fii atent:',
            'Schimbări fizice: Ochii roșii, pupile dilatate sau contractate. Pierdere sau creștere în greutate. Probleme cu somnul. Lipsa igienei personale. Mirosuri neobișnuite pe haine sau în cameră.',
            'Schimbări comportamentale: Lipsa de interes pentru hobby-uri sau activități care îi plăceau înainte. Prieteni noi și misterioși. Minciuni frecvente. Furtul de bani sau obiecte din casă. Absențe nemotivate de la școală, note în scădere. Comportament agresiv sau depresiv.',
            'Schimbări emoționale și psihice: Schimbări bruște de dispoziție. Iritabilitate crescută. Anxietate, paranoia sau episoade de confuzie.',
            'Cum să abordezi discuția cu copilul: Alege momentul potrivit. Fii calm și empatic. Ascultă, nu judeca. Recunoaște-i suferința. Fii un partener, nu un „detectiv".',
            'Cum să-l convingi să meargă la terapie: Propune-i să mergeți împreună. Prezintă terapia ca pe o soluție, nu ca pe o pedeapsă. Fii deschis și transparent.',
            'Important: Nu încerca să gestionezi singur problema. Contactează un specialist în dependențe sau un psihoterapeut cu experiență în lucrul cu adolescenți.',
        ],
    },
    {
        slug: 'cum-poti-sprijini-un-adolescent-dependent',
        title: '🧭 Cum poți sprijini un adolescent care consumă sau e dependent',
        category: 'parents',
        publishedAt: '2025-08-07',
        body: [
            'A descoperi că propriul copil consumă substanțe este o experiență dureroasă și copleșitoare. Totuși, există pași concreți pe care îi poți face.',
            '1. Înțelege situația înainte să acționezi 🔍: Consumul nu apare din senin — de multe ori este o strategie de supraviețuire pentru dureri emoționale, traume sau presiuni sociale. Primul pas nu este pedeapsa, ci înțelegerea contextului. Ține un mic jurnal al observațiilor tale.',
            '2. Creează un plan în familie: Toți membrii familiei trebuie implicați: nu e doar „problema copilului". Stabiliți împreună reguli clare, dar și spații sigure de comunicare. Caută sprijin și pentru tine ca părinte.',
            '3. Consultă profesioniști cât mai repede: Caută un psiholog/psihiatru specializat în adicții la adolescenți. Intervențiile cele mai eficiente sunt terapiile cognitiv-comportamentale (CBT) și terapia motivațională.',
            '4. Colaborarea cu școala: Nu ascunde problema — vorbește cu dirigintele și consilierul școlar. Profesorii pot fi aliați importanți.',
            '5. Ajută-l să găsească alternative sănătoase: Sportul reduce stresul și crește încrederea în sine. Muzica sau arta sunt canale excelente pentru exprimarea emoțiilor. Voluntariatul îi dă sentimentul că are un scop.',
            '6. Creează un mediu fără judecată, dar cu responsabilitate: Nu ajută să spui „Ești un drogat / o rușine". Setează limite clare și consecințe logice. Echilibrul între empatie și fermitate este cheia.',
            '7. Învață să recunoști semnele recăderii: Recăderile fac parte din proces. Fii atent la schimbări bruște de dispoziție, lipsa de interes, anturaj nou suspect.',
            '8. Ai grijă și de tine: Ca părinte, e ușor să cazi în vinovăție sau epuizare. Caută sprijin pentru tine: terapie, grupuri de părinți. Copilul are nevoie de un părinte puternic.',
            'Dependența nu este o rușine și nici un „sfârșit de drum". Este un semnal de alarmă, un strigăt de ajutor al copilului tău. Asociația „Drogurile ucid visurile copiilor" este aici să te sprijine. Ne poți suna la 0750 633 148.',
        ],
    },
    {
        slug: 'pericolele-steroizilor-anabolizanti-la-adolescenti',
        title: '💥 Pericolele steroizilor anabolizanți la adolescenți',
        category: 'health',
        publishedAt: '2025-08-08',
        body: [
            'Steroizii anabolizanți pot lăsa efecte grave și ireversibile asupra adolescenților.',
            '🧬 Ce sunt și de ce sunt periculoși? Steroizii anabolizanți sunt substanțe sintetice, „copii" ale testosteronului. Utilizarea lor fără supraveghere medicală este periculoasă. Dereglează hormonii naturali ai corpului, cu efecte adesea ireversibile.',
            '👶 De ce adolescenții sunt mai vulnerabili: În adolescență, corpul trece prin transformări majore. Intervenția cu steroizi poate opri creșterea în înălțime, crea tulburări hormonale permanente și afecta sănătatea emoțională.',
            '🦴 Efecte asupra creșterii și oaselor: Pot închide prematur cartilajele de creștere, ceea ce duce la oprirea definitivă a creșterii.',
            '❤️ Inima și vasele de sânge: Cresc tensiunea arterială și colesterolul LDL. Riscul de infarct sau AVC poate crește chiar la 17–18 ani.',
            '🩸 Ficatul și rinichii: Ficatul suferă primul: steatoză, icter, colestază, tumori. Rinichii pot dezvolta insuficiență renală cronică.',
            '🧠 Creierul, emoțiile și comportamentul: Pot induce agresivitate, iritabilitate, crize de furie, anxietate, depresie și chiar psihoze.',
            '🔥 Efecte hormonale: La băieți: oprirea producției naturale de testosteron, atrofie testiculară, infertilitate, ginecomastie. La fete: dereglări ale ciclului menstrual, îngroșarea vocii, infertilitate.',
            '📊 Cât de răspândit este: 1–4% dintre adolescenți cu consum cel puțin o dată. Presiunea socială și accesul online cresc riscul.',
            '🛑 Cum spui „NU" presiunii: Pregătește un răspuns simplu: „Nu, cresc natural." Caută un prieten pe aceeași lungime de undă. Prioritizează sănătatea.',
            '💚 Concluzie: Steroizii anabolizanți pun în pericol inima, ficatul, creierul, fertilitatea și echilibrul emoțional. Alege răbdarea și creșterea naturală.',
        ],
    },
    {
        slug: 'despre-seria-mind-matters',
        title: '📘 Despre seria "Mind Matters"',
        category: 'education',
        publishedAt: '2025-08-09',
        body: [
            'Seria Mind Matters a fost realizată de National Institute on Drug Abuse (NIDA) pentru a-i ajuta pe elevi să înțeleagă cum drogurile afectează creierul și corpul.',
            '🎯 Obiectivul principal este ca profesorii să aibă resurse clare și adaptate pentru a discuta cu elevii despre aceste subiecte sensibile, într-un mod științific, dar accesibil.',
            'Seria conține: broșuri pentru elevi (explicații simple + ilustrații atractive), ghidul profesorului (cu idei de discuții și activități interactive), resurse suplimentare pentru aprofundare.',
            '🧑‍🏫 Cum să folosești acest ghid: Ghidul este gândit ca un instrument flexibil, care poate fi folosit la educație pentru sănătate, biologie, științe sociale, ore de dirigenție sau activități extracurriculare.',
            '📌 Ce vei găsi: Explicații clare despre cum afectează fiecare drog creierul și corpul. Întrebări pentru discuții. Activități practice. Resurse suplimentare.',
            '🌟 De ce e util pentru profesori: Îți oferă un limbaj simplu și ușor de transmis elevilor. Te ajută să abordezi un subiect sensibil într-un mod sigur și documentat. Contribuie la construirea unui climat de încredere și prevenție în școală.',
            '🌿 Marijuana (Cannabis): Provine din planta cannabis. Conține peste 100 de substanțe chimice, dar cea mai cunoscută este THC. Adolescenții sunt mult mai vulnerabili pentru că creierul lor este încă în dezvoltare. Consumul regulat poate duce la scăderea concentrării, lipsă de motivație, anxietate și risc crescut de dependență.',
            '🚬 Nicotină și Tutun: Nicotina este o substanță chimică foarte adictivă. Adolescenții sunt deseori atrași de vape-uri cu arome care par „inofensive", dar conțin nicotină și alte substanțe toxice.',
            '🍺 Alcool: Este legal pentru adulți, dar ilegal și periculos pentru minori. Adolescenții pot fi tentați să bea din curiozitate, presiunea grupului sau dorința de a se relaxa.',
            'Asociația „Drogurile ucid visurile copiilor" este alături de profesori, părinți și elevi. Ne puteți contacta la 0750633148.',
        ],
    },
    {
        slug: '6-intrebari-esentiale-despre-dependenta',
        title: '6 Întrebări Esențiale Despre Dependență',
        category: 'education',
        publishedAt: '2025-08-10',
        body: [
            'Bazat pe ideile lui Dr. Gabor Maté — tradus și adaptat pentru publicul larg.',
            '1. Ce este dependența? Dependența nu înseamnă doar consum de droguri sau alcool. Poate fi orice comportament repetitiv care oferă alinare sau plăcere temporară, dar are consecințe negative pe termen lung.',
            '2. Cum influențează mediul dependența? Creierul se dezvoltă în funcție de mediul în care trăim. Copiii au nevoie de siguranță emoțională și conectare. Lipsa unui mediu sigur poate crește vulnerabilitatea la dependență.',
            '3. Ce ne arată experiența copilăriei timpurii? Primele luni și ani de viață sunt decisive pentru dezvoltarea creierului. Chiar și gesturi simple precum îmbrățișările sprijină dezvoltarea sănătoasă.',
            '4. Care este rolul atașamentului parental? Atașamentul sigur cu părinții ajută copilul să își regleze emoțiile și stresul. Fără un atașament stabil, copilul poate dezvolta o predispoziție mai mare spre comportamente de dependență.',
            '5. Cum contribuie trauma la dependență? Majoritatea persoanelor dependente au trecut prin traume în copilărie. Fiecare experiență traumatică crește riscul de consum precoce de 2–4 ori.',
            '6. Care este rolul stresului? Stresul cronic afectează creierul. Copiii expuși la stres devin adulți mai predispuși să caute alinare rapidă în comportamente adictive.',
            'Concluzie: Dependența nu este un defect de caracter, ci o încercare de a face față durerii și stresului. Creierul se poate vindeca prin relații sigure, sprijin și terapie.',
        ],
    },
    {
        slug: 'atasamentul-si-ingrijirea-in-copilarie',
        title: '🌱 Atașamentul și îngrijirea în copilărie',
        category: 'health',
        publishedAt: '2025-08-11',
        body: [
            'Dragostea, contactul și grija de zi cu zi construiesc literalmente creierul copilului.',
            'Atunci când un bebeluș primește dragoste, zâmbete și atingeri blânde de la părinți, creierul lui eliberează „substanțe ale fericirii" (endorfine). Acestea îl ajută să se simtă în siguranță și îi dezvoltă circuitele din creier care mai târziu vor regla plăcerea, motivația și capacitatea de a se conecta cu ceilalți.',
            'În schimb, atunci când copilul trece prin lipsă de atenție, absența părinților sau situații stresante, creierul său dezvoltă mai puțini receptori pentru aceste „substanțe ale bucuriei". Asta îl face mai vulnerabil la anxietate și, mai târziu, la tentația de a apela la substanțe.',
            'Studiile pe animale au arătat lucruri uimitoare: puii de maimuță separați de mamă doar câteva zile aveau modificări serioase în creier; șobolanii ținuți în izolare de mici erau mai predispuși ca adulți să consume cocaină; dimpotrivă, cei care au primit multă îngrijire au dezvoltat creiere mai rezistente la stres.',
            'Pentru copii, prezența și afecțiunea părinților sunt la fel de vitale ca mâncarea și apa. Bebelușii prematuri cresc mai repede și mai sănătos atunci când sunt atinși și mângâiați câteva minute pe zi.',
            'Concluzie: dragostea, contactul și grija de zi cu zi construiesc literalmente creierul copilului. Fără ele, copilul poate rămâne cu un gol emoțional pe care, mai târziu, ar putea încerca să îl umple cu substanțe.',
        ],
    },
    {
        slug: 'trauma-din-copilarie-si-riscul-de-dependenta',
        title: '🌪️ Trauma din copilărie și riscul de dependență',
        category: 'health',
        publishedAt: '2025-08-12',
        body: [
            'Majoritatea celor care ajung dependenți au trecut prin forme de traumă în copilărie.',
            'Studiile arată clar: majoritatea celor care ajung dependenți au trecut prin forme de traumă în copilărie — abuz fizic, emoțional, sexual sau neglijare. Cercetarea ACE a descoperit că fiecare experiență grea din copilărie crește de 2–4 ori șansele de a începe devreme consumul de substanțe. Dacă un copil trece prin 5 sau mai multe traume, riscul ajunge și de 10 ori mai mare.',
            'Aproape două treimi din cazurile de consum de droguri injectabile își au rădăcina în traumele din copilărie. Trauma nu alege clase sociale.',
            'În cazul alcoolului, adolescenții care au fost abuzați sexual au de 3 ori mai multe șanse să înceapă să bea devreme. Pentru fiecare traumă emoțională trăită în copilărie, șansele de abuz de alcool cresc de 2–3 ori.',
            'Trauma lasă urme și în creier: Copiii abuzați au creierul cu 7–8% mai mic decât normal. Hipocampul poate fi mai mic cu 15%. „Corpus callosum" – puntea dintre emisferele cerebrale – e afectată.',
            'Concluzia: Trauma din copilărie nu este doar un „episod trecut", ci modelează modul în care creierul și emoțiile funcționează toată viața, crescând masiv riscul de dependență.',
            'Text adaptat din articolul „Addiction: Childhood Trauma, Stress and the Biology of Addiction", scris de dr. Gabor Maté, publicat în Journal of Restorative Medicine (2012).',
        ],
    },
    {
        slug: 'stresul-si-dependenta',
        title: '😰 Stresul și dependența',
        category: 'health',
        publishedAt: '2025-08-13',
        body: [
            'Dependența este, în mare parte, o încercare de a face față stresului.',
            'Ce este stresul? Stresul e felul în care corpul și mintea reacționează atunci când simt că nu mai pot face față. Se eliberează hormoni ca adrenalina și cortizolul, care afectează inima, plămânii, mușchii și mai ales creierul. Cel mai mare stres pentru oameni nu e lipsa banilor, ci frica de a pierde dragostea și siguranța emoțională.',
            'Cum influențează stresul din copilărie? Dacă un copil trece prin mult stres sau traumă devreme, creierul lui se „setează" pe modul alert permanent. Ca adult, se va stresa mult mai repede și mai intens.',
            'De ce apare dependența? Un creier obișnuit să fie mereu tensionat caută soluții rapide pentru alinare. Drogurile, alcoolul sau alte comportamente oferă această alinare pe moment, dar pe termen lung distrug și mai mult echilibrul.',
            'Persoanele care au trecut prin stres sever în copilărie sunt mai vulnerabile: se declanșează foarte ușor în fața stresului, hormonii stresului se „leagă" de pofta pentru droguri, stresul duce adesea la recăderi.',
            'Ce factori ne stresează cel mai mult? Incertitudinea, lipsa de informații, pierderea controlului. La acestea se adaugă conflictele nerezolvate și singurătatea.',
            'Pe scurt: Dependența este o încercare de a face față stresului. Deși soluția aleasă dă alinare rapidă, pe termen lung aduce și mai multă durere.',
            'Text adaptat din articolul „Addiction: Childhood Trauma, Stress and the Biology of Addiction", scris de dr. Gabor Maté.',
        ],
    },
    {
        slug: 'anxietatea-trauma-si-puterea-iubirii-de-sine',
        title: 'Anxietatea, trauma și puterea vindecătoare a iubirii de sine',
        category: 'health',
        publishedAt: '2025-08-14',
        body: [
            'Anxietatea este o emoție normală, apărută ca să ne protejeze, chiar dacă uneori exagerează pericolele.',
            'Înțelegerea anxietății: Ea „vrea" să ajute, dar o face zgomotos și apăsător. Dacă te lupți cu ea, devine mai puternică, însă dacă o accepți și o lași să existe, ea va pierde din intensitate. Privită ca un semnal, nu ca un dușman, anxietatea devine mai ușor de purtat.',
            'Gândurile anxioase: Un aspect important este că gândurile pe care le aduce anxietatea nu sunt mereu adevărate. Ele pot fi interpretări distorsionate. În loc să le iei de bune, poți să le scrii și să le reformulezi în variante mai blânde.',
            'Traumele — mari și mici: Gabor Maté vorbește despre traumele cu „T" mare – cele evidente, șocante – și traumele cu „t" mic, mai subtile, dar la fel de importante. Acestea din urmă apar atunci când ceva esențial lipsește, cum ar fi afecțiunea sau sentimentul de siguranță.',
            'Procesarea traumelor: Indiferent de mărimea lor, traumele tulbură echilibrul interior. Încercarea de a le ignora nu face decât să le mențină vii. Calea sănătoasă este să avem curajul să ne uităm la ele, cu sprijinul unui specialist.',
            'Puterea vindecătoare a iubirii: Iubirea este una dintre cele mai puternice forțe de vindecare. Relațiile sănătoase ne dau siguranță și ne ajută să ne regăsim echilibrul. La fel de importantă este iubirea de sine: capacitatea de a ne trata cu blândețe și de a ne respecta propriile nevoi.',
            'Vindecarea începe cu acceptarea și compasiunea pentru noi înșine.',
        ],
    },
    {
        slug: 'intelegerea-emotiilor',
        title: 'Înțelegerea emoțiilor – info de bază și practici utile',
        category: 'education',
        author: 'Diana Todeanca',
        publishedAt: '2025-08-15',
        body: [
            'Toate emoțiile au un rol. Acceptarea lor e esențială pentru sănătatea psihică.',
            'Iată ce ar trebui să știi: Toate emoțiile au un rol și un rost în viața noastră. Au nevoie de atenția noastră – ne transmit mesaje importante. Ajută să le denumim și să vorbim despre ele. Nu evita emoțiile neplăcute. Emoțiile sunt o formă de inteligență emoțională.',
            'Tristețea: O reacție la pierdere, respingere sau dezamăgire. Cere ajutor și vorbește cu cineva. Dă-ți voie să plângi. Odihnește-te, notează-ți gândurile, fă mișcare. Dacă e intensă și prelungită (>2 luni), mergi la psihiatru.',
            'Furia: Reacție la nedreptate sau încălcarea limitelor. Spune ce ai nevoie. Eliberează energia prin sport, dans. Respectă 3 reguli: nu te răni pe tine, nu îi răni pe ceilalți, nu distruge.',
            'Frica și anxietatea: Frica e reacție la pericol real; anxietatea e „frica fără obiect". Evaluează realist pericolul. Respirație controlată, relaxare, meditație, mișcare.',
            'Fericirea și dezgustul: Fericirea te orientează spre ce îți face bine. Dezgustul te protejează de ceea ce e toxic. Fă o listă cu lucruri care îți aduc bucurie.',
            'Vinovăția și rușinea: Vinovăția te ajută să corectezi. Rușinea este socială și se dizolvă vorbind despre ea. Fă diferența: „am greșit" (vinovăție) vs „sunt rău/rea" (rușine).',
            'Dă-ți voie să simți. Tendința de a bloca emoțiile le intensifică. Emoțiile vin, stau puțin și trec – sunt cheia pentru sănătate și relații bune.',
        ],
    },
    {
        slug: 'hipnoza-regresiva-vindecarea-dependentelor',
        title: 'Hipnoza regresivă – sprijin profund în procesul de vindecare a dependențelor',
        category: 'health',
        author: 'Mihaela Sava',
        publishedAt: '2025-08-16',
        body: [
            'Dependențele de droguri și alte substanțe reprezintă adesea o manifestare a unei suferințe emoționale profunde.',
            'Dincolo de comportamentele vizibile, ele pot avea rădăcini în traume nerezolvate, răni emoționale vechi sau chiar în tipare transgeneraționale moștenite inconștient.',
            'Hipnoza regresivă oferă o abordare terapeutică blândă și eficientă, care sprijină procesul de vindecare din interior, accesând direct nivelurile profunde ale subconștientului.',
            'Într-o stare de relaxare și siguranță, persoana este ghidată să exploreze originea emoțională a dependenței, pentru a înțelege, elibera și transforma acele experiențe care au creat vulnerabilitatea inițială.',
            'Prin acest proces, hipnoza regresivă poate contribui la: conștientizarea și vindecarea traumelor emoționale din copilărie; înțelegerea legăturilor transgeneraționale; restabilirea conexiunii cu sinele autentic; reprogramarea subconștientului pentru a susține alegeri sănătoase.',
            'Hipnoza regresivă nu înlocuiește tratamentele medicale, dar le poate completa în mod benefic, oferind o înțelegere mai profundă a cauzelor interioare și facilitând procesul de recuperare.',
            'Prin accesarea și vindecarea sursei emoționale a dependenței, persoana poate recăpăta sentimentul de libertate, echilibru și sens în propria viață.',
        ],
    },
    {
        slug: 'ghid-complet-despre-droguri-pentru-parinti',
        title: 'Ghid complet despre droguri pentru Părinți: Droguri, Simptome și Semne de Alarmă',
        category: 'guide',
        publishedAt: '2025-08-17',
        body: [
            'Scris într-un limbaj prietenos, ca să știi la ce să fii atent(ă). Acest ghid este realizat pentru a-i ajuta pe părinți să înțeleagă ce tipuri de substanțe pot consuma adolescenții, cum sunt denumite în argou, ce emojiuri folosesc online, ce efecte au și care sunt simptomele.',
            'Cannabis (marijuana, hașiș): Argou: iarbă, verde, marij, ganja, joint. Emojiuri: 🍁, 🌿, 💨. Preț: 30–70 lei/gram. Cel mai folosit drog la adolescenți. Efecte: scade motivația, memoria și concentrarea. Simptome: ochi roșii, miros specific, apetit crescut.',
            'MDMA / Ecstasy: Argou: E, Molly, pastile. Emojiuri: 💊, 🍬. Preț: 40–60 lei/pastilă. Stimulant sintetic popular la petreceri. Simptome: transpirație excesivă, scrâșnit din dinți.',
            'Amfetamine / Metamfetamine: Argou: speed, crystal, meth. Emojiuri: ⚡, 💎, ❄️. Preț: 50–100 lei/gram. Stimulente puternice, extrem de adictive. Simptome: pupile dilatate, lipsă somn, ticuri nervoase.',
            'Mephedrone / Cathinone / Etno: Argou: miau-miau, magic, sare. Preț: 10–30 lei/doză. Stimulente sintetice ce imită amfetaminele. Simptome: agitație, comportament agresiv.',
            'Cocaină: Argou: albă, praf, zăpadă, coke. Preț: 350–500 lei/gram. Stimulant puternic, dependență rapidă. Simptome: pupile dilatate, energie excesivă urmată de cădere emoțională.',
            'Heroină: Argou: H, junk, maro. Preț: 20–50 lei/doză. Opioid extrem de adictiv. Simptome: urme de înțepături, somnolență extremă, pupile foarte mici.',
            'Benzodiazepine (Xanax, Klonopin): Argou: benzos, bars. Preț: 10–50 lei/pastilă. Medicamente pentru anxietate, abuzate pentru sedare. Simptome: vorbire neclară, mers dezechilibrat.',
            'Codeină / Lean: Argou: lean, purple drank. Preț: 50–100 lei/sticlă. Sirop de tuse cu codeină. Simptome: somnolență, vorbire lentă.',
            'Calvin Klein (CK): Combinație de cocaină și ketamină. Extrem de periculoasă. Simptome: comportament haotic, confuzie.',
            'Candyflipping: LSD + MDMA. Foarte riscantă. Simptome: halucinații intense, atacuri de panică.',
            'Ketamină: Argou: Special K. Anestezic folosit ilegal. Simptome: mers nesigur, privire goală.',
            'GHB / Rohypnol: „Drogul violului". Simptome: sedare profundă, amnezie.',
            'Protoxid de azot: Argou: balon. Preț: 5–10 lei/capsulă. Produce euforie de câteva secunde. Simptome: amețeli, râs necontrolat.',
            'Inhalanți (aracet, benzină, diluant): Foarte toxice. Simptome: miros puternic pe haine, amețeli.',
            'Fentanil: Opioid sintetic de 50–100 ori mai puternic decât morfina. Cea mai mare amenințare actuală. Doze minime pot fi fatale.',
        ],
    },
    {
        slug: 'plan-strategic-asociatia',
        title: 'Plan Strategic - Asociația Drogurile ucid visurile copiilor',
        category: 'education',
        publishedAt: '2025-08-18',
        body: [
            'Asociația „Drogurile ucid visurile copiilor" este o inițiativă națională dedicată prevenirii consumului de substanțe și sprijinirii copiilor și tinerilor afectați.',
            'Credem cu tărie că fiecare copil merită o șansă reală la o viață sănătoasă, echilibrată și plină de speranță.',
            'Misiunea noastră: Ne propunem să fim o voce puternică în lupta împotriva consumului de substanțe, să schimbăm percepția socială despre consumatori și să oferim sprijin real copiilor și familiilor lor.',
            'Obiectivele principale: Schimbarea percepției sociale despre consumatori. Acceptarea socială a consumatorului. Dezvoltarea și promovarea unor unelte de identificare a consumatorului.',
            'Cea mai mare campanie antidrog din România: Pe 1 septembrie vom lansa oficial cea mai mare campanie națională antidrog din România. Participă influenceri, sportivi, foști consumatori, psihologi, televiziuni, școli și organizații.',
            'Centrul nostru — Fermă-Școală: Unul dintre cele mai importante proiecte este construirea unui centru tip fermă-școală la Sibiu. Va include psihologi specializați, nutriționiști, mentori (foști consumatori), activități practice și colaborare cu clinici.',
            'Reintegrarea în societate: După recuperare, tinerii vor fi sprijiniți prin dezvoltarea unei firme de recrutare dedicate beneficiarilor.',
            'Contact: drogurileucidvisurilecopiilor@gmail.com, tel: (0757) 254 316.',
            'Împreună suntem mai puternici și putem construi o lume mai bună pentru copiii noștri.',
        ],
    },
    {
        slug: 'campanie-nationala-1-septembrie',
        title: 'Asociația „Drogurile ucid visurile copiilor" lansează o campanie națională pe 1 septembrie',
        category: 'prevention',
        publishedAt: '2025-08-19',
        body: [
            'Asociația Drogurile ucid visurile copiilor anunță lansarea unei campanii naționale de conștientizare, care va începe pe 1 septembrie 2025, la ora 12:00.',
            'Scopul campaniei este de a atrage atenția asupra pericolelor tuturor tipurilor de dependențe – fie că vorbim despre substanțe interzise, alcool, fumat, jocuri de noroc sau chiar dependențe digitale – și de a proteja viitorul copiilor și tinerilor din România.',
            'Asociația își propune să devină o voce puternică în lupta pentru prevenirea și reducerea dependențelor, oferind atât informații corecte și accesibile, cât și exemple reale.',
            'Mesajul central: „Dependențele ucid visurile copiilor, dar împreună putem să le protejăm."',
            'Susținători ai campaniei: Ilie Năstase, Irina Margareta Nistor, Toma Cuzin, Johnny Romano, Călin Donca, Liviu Vârciu, Marian Drăgulescu (alături de Academia lui de gimnastică), Academia de Fotbal Alma-Sibiu, Clinica Aria din Sibiu și mulți alți influenceri.',
            'Prin această campanie, ne dorim să creăm o mișcare națională în care fiecare județ, fiecare comunitate și fiecare familie să se implice activ.',
            'Contact pentru colaborări: 0730 173 727. Împreună, putem construi o Românie în care copiii cresc liberi și cu visurile intacte.',
        ],
    },
    {
        slug: 'tu-parinte-esti-solutia',
        title: 'Tu, părinte, ești soluția!',
        category: 'parents',
        publishedAt: '2025-08-20',
        body: [
            'Părinții pot fi ancora care schimbă destinul unui adolescent.',
            'O lume diferită: Trăim într-o lume diferită de cea în care ați crescut voi, părinții. Drogurile, alcoolul, presiunea socială și izolarea emoțională sunt mult mai aproape de copii decât ne imaginăm.',
            'Când afli că adolescentul consumă: Nu este doar un semnal de alarmă pentru el, ci și pentru tine. Tu ești soluția. Copilul tău are nevoie de tine, nu de pedeapsă, nu de amenințări.',
            'De ce au nevoie adolescenții: Înțelegere, siguranță și un spațiu în care să fie ascultați fără judecată. Dacă nu găsesc asta acasă, vor căuta în altă parte.',
            'Schimbarea de perspectivă: Fii curios, nu critic. Pune întrebări deschise, ascultă răspunsurile. Sprijină-l să descopere alte modalități de a face față durerii.',
            'Mesajul final: Părinții au puterea de a fi ancora care salvează. Uneori, simplul fapt că adolescentul știe că „mama și tata nu renunță la mine" poate face diferența dintre o prăbușire și o renaștere.',
        ],
    },
]
